services:
# setup postgres database
  db:
    image: "postgres:16"
    environment: 
    # better practice: use .env files storing the information and add them to gitignore
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_USER=alex
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
       - "5432:5432"

# setup the etl script

  etl:
    # this will build the Dockerfile in the current directory 
    build: .  
    
    # use an environment variable for database connection. Better: use .env file
    environment:
      - DB_URL=postgresql+psycopg2://alex:hunter2@db:5432/shelter

    # our etl script requires a command line argument pointing to the csv
    # generally, this will instead be given in e.g. a configuration file 
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv  
    depends_on:
      - db


volumes:
  db_data:
